<?php
// Project constants
return [
    'guestAllowedRoute' => [
        'login',
        'register',
        'password.reset',
        'password.request',
        'password.confirm',
        'verification.notice',
        'verification.verify',
    ],
    'common_css' => [
        'rent_date' => [
            'label_Class' => 'block font-bold mb-2',

            'empty_label' => 'flex',
            'valid_label' => 'flex ml-1 font-medium text-blue-500 ',
            'error_label' => 'flex ml-1 font-medium text-red-500 ',

            'empty_input' => 'w-full p-2 border rounded-md',
            'valid_input' => 'w-full p-2 border rounded-md border-blue-500',
            'error_input' => 'w-full p-2 border rounded-md border-red-500 focus:border-red-500 focus:ring-red-500',

            'empty_checkbox' => 'ml-2',
            'valid_checkbox' => 'ml-2 border border-blue-500',
            'error_checkbox' => 'ml-2 border border-red-500 focus:border-red-500 focus:ring-red-500',

            'empty_checkbox1' => 'flex mt-2',
            'valid_checkbox1' => 'flex mt-2 border border-blue-500',
            'error_checkbox1' => 'flex mt-2 border border-red-500 focus:border-red-500 focus:ring-red-500',
        ],
        'choose_car' => [
            'empty_input' => 'w-full',
            'valid_input' => 'w-full',
            'error_input' => 'w-full',
        ],
        'additional_services' => [
            'empty_label' => 'flex',
            'valid_label' => 'flex ml-1 font-medium text-blue-500 ',
            'error_label' => 'flex ml-1 font-medium text-red-500 ',

            'empty_checkbox' => '',
            'valid_checkbox' => 'border border-blue-500',
            'error_checkbox' => 'border border-red-500 focus:border-red-500 focus:ring-red-500',
        ],
        'check_out' => [
            'empty_label' => 'flex',
            'valid_label' => 'flex ml-1 font-medium text-blue-500 ',
            'error_label' => 'flex ml-1 font-medium text-red-500 ',

            'empty_input' => 'w-50 mb-2 p-2',
            'valid_input' => 'w-50 mb-2 p-2 border border-blue-500',
            'error_input' => 'w-50 mb-2 p-2 border border-red-500 focus:border-red-500 focus:ring-red-500',

            'empty_checkbox' => '',
            'valid_checkbox' => 'border border-blue-500',
            'error_checkbox' => 'border border-red-500 focus:border-red-500 focus:ring-red-500',

            'empty_select' => 'w-full',
            'valid_select' => 'w-full border border-blue-500',
            'error_select' => 'w-full border border-red-500 focus:border-red-500 focus:ring-red-500',
        ],
        'calendar_modal_form' => [
            'empty_label' => 'flex',
            'valid_label' => 'flex ml-1 font-medium text-blue-500 ',
            'error_label' => 'flex ml-1 font-medium text-red-500 ',

            'empty_input' => 'w-full mb-2 p-2',
            'valid_input' => 'w-full mb-2 p-2 border border-blue-500',
            'error_input' => 'w-full mb-2 p-2 border border-red-500 focus:border-red-500 focus:ring-red-500',

            'empty_textarea' => 'w-full text-gray-700 border border-slate-200 rounded py-3 px-4 mb-4 leading-tight focus:outline-none',
            'valid_textarea' => 'w-full text-gray-700 border border-blue-500 rounded py-3 px-4 mb-4 leading-tight focus:outline-none',
            'error_textarea' => 'w-full text-gray-700 border border-red-500 focus:border-red-500 focus:ring-red-500 rounded py-3 px-4 mb-4 leading-tight focus:outline-none',

            'empty_select' => 'w-full',
            'valid_select' => 'w-full border border-blue-500',
            'error_select' => 'w-full border border-red-500 focus:border-red-500 focus:ring-red-500',
        ],
        'contact' => [
            'empty_label' => 'flex',
            'valid_label' => 'flex ml-1 font-medium text-blue-500 ',
            'error_label' => 'flex ml-1 font-medium text-red-500 ',

            'empty_input' => 'w-full text-gray-700 border border-slate-200 rounded py-3 px-4 mb-4 leading-tight focus:outline-none',
            'valid_input' => 'w-full text-gray-700 border border-blue-500 rounded py-3 px-4 mb-4 leading-tight focus:outline-none',
            'error_input' => 'w-full text-gray-700 border border-red-500 focus:border-red-500 focus:ring-red-500 rounded py-3 px-4 mb-4 leading-tight focus:outline-none',

            'empty_textarea' => 'w-full text-gray-700 border border-slate-200 rounded py-3 px-4 mb-4 leading-tight focus:outline-none',
            'valid_textarea' => 'w-full text-gray-700 border border-blue-500 rounded py-3 px-4 mb-4 leading-tight focus:outline-none',
            'error_textarea' => 'w-full text-gray-700 border border-red-500 focus:border-red-500 focus:ring-red-500 rounded py-3 px-4 mb-4 leading-tight focus:outline-none',

        ],
        'home_page_contact' => [
            'empty_input' => 'appearance-none bg-[#161321] w-full py-6 px-3 text-[#777] leading-tight focus:outline-none focus:bg-[#120f1c] rounded-t-lg',
            'valid_input' => 'appearance-none bg-[#161321] w-full py-6 px-3 text-[#777] leading-tight focus:outline-none focus:bg-[#120f1c] rounded-t-lg',
            'error_input' => 'appearance-none bg-[#161321] w-full py-6 px-3 text-[#777] leading-tight focus:outline-none focus:bg-[#120f1c] rounded-t-lg',
        ],
        'modal_inputs' => [
            'empty_label' => 'flex',
            'valid_label' => 'flex ml-1 font-medium text-blue-500 ',
            'error_label' => 'flex ml-1 font-medium text-red-500 ',

            'empty_input' => 'w-full mb-2 p-2',
            'valid_input' => 'w-full mb-2 p-2 border border-blue-500',
            'error_input' => 'w-full mb-2 p-2 border border-red-500 focus:border-red-500 focus:ring-red-500',

            'empty_checkbox' => '',
            'valid_checkbox' => 'border border-blue-500',
            'error_checkbox' => 'border border-red-500 focus:border-red-500 focus:ring-red-500',

            'empty_select' => 'w-full',
            'valid_select' => 'w-full border border-blue-500',
            'error_select' => 'w-full border border-red-500 focus:border-red-500 focus:ring-red-500',
        ],
    ],
    'modal_generic_colors' => [
        'green' => 'text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800',
        'blue' => 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800',
        'red' => 'text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800',
        'purple' => 'text-white bg-[#7963e0] hover:bg-opacity-80 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-800',
    ],
    'all_country_options' => [
        'Romania_default' => 'Romania',
        'Afghanistan' => 'Afghanistan',
        'Åland Islands' => 'Åland Islands',
        'Albania' => 'Albania',
        'Algeria' => 'Algeria',
        'American Samoa' => 'American Samoa',
        'Andorra' => 'Andorra',
        'Angola' => 'Angola',
        'Anguilla' => 'Anguilla',
        'Antarctica' => 'Antarctica',
        'Antigua and Barbuda' => 'Antigua and Barbuda',
        'Argentina' => 'Argentina',
        'Armenia' => 'Armenia',
        'Aruba' => 'Aruba',
        'Australia' => 'Australia',
        'Austria' => 'Austria',
        'Azerbaijan' => 'Azerbaijan',
        'Bahamas' => 'Bahamas',
        'Bahrain' => 'Bahrain',
        'Bangladesh' => 'Bangladesh',
        'Barbados' => 'Barbados',
        'Belarus' => 'Belarus',
        'Belgium' => 'Belgium',
        'Belize' => 'Belize',
        'Benin' => 'Benin',
        'Bermuda' => 'Bermuda',
        'Bhutan' => 'Bhutan',
        'Bolivia' => 'Bolivia',
        'Bosnia and Herzegovina' => 'Bosnia and Herzegovina',
        'Botswana' => 'Botswana',
        'Bouvet Island' => 'Bouvet Island',
        'Brazil' => 'Brazil',
        'British Indian Ocean Territory' => 'British Indian Ocean Territory',
        'Brunei Darussalam' => 'Brunei Darussalam',
        'Bulgaria' => 'Bulgaria',
        'Burkina Faso' => 'Burkina Faso',
        'Burundi' => 'Burundi',
        'Cambodia' => 'Cambodia',
        'Cameroon' => 'Cameroon',
        'Canada' => 'Canada',
        'Cape Verde' => 'Cape Verde',
        'Cayman Islands' => 'Cayman Islands',
        'Central African Republic' => 'Central African Republic',
        'Chad' => 'Chad',
        'Chile' => 'Chile',
        'China' => 'China',
        'Christmas Island' => 'Christmas Island',
        'Cocos (Keeling) Islands' => 'Cocos (Keeling) Islands',
        'Colombia' => 'Colombia',
        'Comoros' => 'Comoros',
        'Congo' => 'Congo',
        'Congo, The Democratic Republic of The' => 'Congo, The Democratic Republic of The',
        'Cook Islands' => 'Cook Islands',
        'Costa Rica' => 'Costa Rica',
        "Cote D'ivoire" => "Cote D'ivoire",
        'Croatia' => 'Croatia',
        'Cuba' => 'Cuba',
        'Cyprus' => 'Cyprus',
        'Czech Republic' => 'Czech Republic',
        'Denmark' => 'Denmark',
        'Djibouti' => 'Djibouti',
        'Dominica' => 'Dominica',
        'Dominican Republic' => 'Dominican Republic',
        'Ecuador' => 'Ecuador',
        'Egypt' => 'Egypt',
        'El Salvador' => 'El Salvador',
        'Equatorial Guinea' => 'Equatorial Guinea',
        'Eritrea' => 'Eritrea',
        'Estonia' => 'Estonia',
        'Ethiopia' => 'Ethiopia',
        'Falkland Islands (Malvinas)' => 'Falkland Islands (Malvinas)',
        'Faroe Islands' => 'Faroe Islands',
        'Fiji' => 'Fiji',
        'Finland' => 'Finland',
        'France' => 'France',
        'French Guiana' => 'French Guiana',
        'French Polynesia' => 'French Polynesia',
        'French Southern Territories' => 'French Southern Territories',
        'Gabon' => 'Gabon',
        'Gambia' => 'Gambia',
        'Georgia' => 'Georgia',
        'Germany' => 'Germany',
        'Ghana' => 'Ghana',
        'Gibraltar' => 'Gibraltar',
        'Greece' => 'Greece',
        'Greenland' => 'Greenland',
        'Grenada' => 'Grenada',
        'Guadeloupe' => 'Guadeloupe',
        'Guam' => 'Guam',
        'Guatemala' => 'Guatemala',
        'Guernsey' => 'Guernsey',
        'Guinea' => 'Guinea',
        'Guinea-bissau' => 'Guinea-bissau',
        'Guyana' => 'Guyana',
        'Haiti' => 'Haiti',
        'Heard Island and Mcdonald Islands' => 'Heard Island and Mcdonald Islands',
        'Holy See (Vatican City State)' => 'Holy See (Vatican City State)',
        'Honduras' => 'Honduras',
        'Hong Kong' => 'Hong Kong',
        'Hungary' => 'Hungary',
        'Iceland' => 'Iceland',
        'India' => 'India',
        'Indonesia' => 'Indonesia',
        'Iran, Islamic Republic of' => 'Iran, Islamic Republic of',
        'Iraq' => 'Iraq',
        'Ireland' => 'Ireland',
        'Isle of Man' => 'Isle of Man',
        'Israel' => 'Israel',
        'Italy' => 'Italy',
        'Jamaica' => 'Jamaica',
        'Japan' => 'Japan',
        'Jersey' => 'Jersey',
        'Jordan' => 'Jordan',
        'Kazakhstan' => 'Kazakhstan',
        'Kenya' => 'Kenya',
        'Kiribati' => 'Kiribati',
        'Kuwait' => 'Kuwait',
        'Kyrgyzstan' => 'Kyrgyzstan',
        'Latvia' => 'Latvia',
        'Lebanon' => 'Lebanon',
        'Lesotho' => 'Lesotho',
        'Liberia' => 'Liberia',
        'Libyan Arab Jamahiriya' => 'Libyan Arab Jamahiriya',
        'Liechtenstein' => 'Liechtenstein',
        'Lithuania' => 'Lithuania',
        'Luxembourg' => 'Luxembourg',
        'Macao' => 'Macao',
        'Macedonia, The Former Yugoslav Republic of' => 'Macedonia, The Former Yugoslav Republic of',
        'Madagascar' => 'Madagascar',
        'Malawi' => 'Malawi',
        'Malaysia' => 'Malaysia',
        'Maldives' => 'Maldives',
        'Mali' => 'Mali',
        'Malta' => 'Malta',
        'Marshall Islands' => 'Marshall Islands',
        'Martinique' => 'Martinique',
        'Mauritania' => 'Mauritania',
        'Mauritius' => 'Mauritius',
        'Mayotte' => 'Mayotte',
        'Mexico' => 'Mexico',
        'Micronesia, Federated States of' => 'Micronesia, Federated States of',
        'Moldova, Republic of' => 'Moldova, Republic of',
        'Monaco' => 'Monaco',
        'Mongolia' => 'Mongolia',
        'Montenegro' => 'Montenegro',
        'Montserrat' => 'Montserrat',
        'Morocco' => 'Morocco',
        'Mozambique' => 'Mozambique',
        'Myanmar' => 'Myanmar',
        'Namibia' => 'Namibia',
        'Nauru' => 'Nauru',
        'Nepal' => 'Nepal',
        'Netherlands' => 'Netherlands',
        'Netherlands Antilles' => 'Netherlands Antilles',
        'New Caledonia' => 'New Caledonia',
        'New Zealand' => 'New Zealand',
        'Nicaragua' => 'Nicaragua',
        'Niger' => 'Niger',
        'Nigeria' => 'Nigeria',
        'Niue' => 'Niue',
        'Norfolk Island' => 'Norfolk Island',
        'Northern Mariana Islands' => 'Northern Mariana Islands',
        'Norway' => 'Norway',
        'Oman' => 'Oman',
        'Pakistan' => 'Pakistan',
        'Palau' => 'Palau',
        'Palestinian Territory, Occupied' => 'Palestinian Territory, Occupied',
        'Panama' => 'Panama',
        'Papua New Guinea' => 'Papua New Guinea',
        'Paraguay' => 'Paraguay',
        'Peru' => 'Peru',
        'Philippines' => 'Philippines',
        'Pitcairn' => 'Pitcairn',
        'Poland' => 'Poland',
        'Portugal' => 'Portugal',
        'Puerto Rico' => 'Puerto Rico',
        'Qatar' => 'Qatar',
        'Reunion' => 'Reunion',
        'Romania' => 'Romania',
        'Russian Federation' => 'Russian Federation',
        'Rwanda' => 'Rwanda',
        'Saint Helena' => 'Saint Helena',
        'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
        'Saint Lucia' => 'Saint Lucia',
        'Saint Pierre and Miquelon' => 'Saint Pierre and Miquelon',
        'Saint Vincent and The Grenadines' => 'Saint Vincent and The Grenadines',
        'Samoa' => 'Samoa',
        'San Marino' => 'San Marino',
        'Sao Tome and Principe' => 'Sao Tome and Principe',
        'Saudi Arabia' => 'Saudi Arabia',
        'Senegal' => 'Senegal',
        'Serbia' => 'Serbia',
        'Seychelles' => 'Seychelles',
        'Sierra Leone' => 'Sierra Leone',
        'Singapore' => 'Singapore',
        'Slovakia' => 'Slovakia',
        'Slovenia' => 'Slovenia',
        'Solomon Islands' => 'Solomon Islands',
        'Somalia' => 'Somalia',
        'South Africa' => 'South Africa',
        'South Georgia and The South Sandwich Islands' => 'South Georgia and The South Sandwich Islands',
        'Spain' => 'Spain',
        'Sri Lanka' => 'Sri Lanka',
        'Sudan' => 'Sudan',
        'Suriname' => 'Suriname',
        'Svalbard and Jan Mayen' => 'Svalbard and Jan Mayen',
        'Swaziland' => 'Swaziland',
        'Sweden' => 'Sweden',
        'Switzerland' => 'Switzerland',
        'Syrian Arab Republic' => 'Syrian Arab Republic',
        'Taiwan' => 'Taiwan',
        'Tajikistan' => 'Tajikistan',
        'Tanzania, United Republic of' => 'Tanzania, United Republic of',
        'Thailand' => 'Thailand',
        'Timor-leste' => 'Timor-leste',
        'Togo' => 'Togo',
        'Tokelau' => 'Tokelau',
        'Tonga' => 'Tonga',
        'Trinidad and Tobago' => 'Trinidad and Tobago',
        'Tunisia' => 'Tunisia',
        'Turkey' => 'Turkey',
        'Turkmenistan' => 'Turkmenistan',
        'Turks and Caicos Islands' => 'Turks and Caicos Islands',
        'Tuvalu' => 'Tuvalu',
        'Uganda' => 'Uganda',
        'Ukraine' => 'Ukraine',
        'United Arab Emirates' => 'United Arab Emirates',
        'United Kingdom' => 'United Kingdom',
        'United States' => 'United States',
        'United States Minor Outlying Islands' => 'United States Minor Outlying Islands',
        'Uruguay' => 'Uruguay',
        'Uzbekistan' => 'Uzbekistan',
        'Vanuatu' => 'Vanuatu',
        'Venezuela' => 'Venezuela',
        'Viet Nam' => 'Viet Nam',
        'Virgin Islands, British' => 'Virgin Islands, British',
        'Virgin Islands, U.S.' => 'Virgin Islands, U.S.',
        'Wallis and Futuna' => 'Wallis and Futuna',
        'Western Sahara' => 'Western Sahara',
        'Yemen' => 'Yemen',
        'Zambia' => 'Zambia',
        'Zimbabwe' => 'Zimbabwe',
    ],
    'all_county_options' => [
        'Alba' => 'Alba',
        'Arad' => 'Arad',
        'Arges' => 'Arges',
        'Bacau' => 'Bacau',
        'Bihor' => 'Bihor',
        'Bistrita Nasaud' => 'Bistrita Nasaud',
        'Botosani' => 'Botosani',
        'Brasov' => 'Brasov',
        'Braila' => 'Braila',
        'Bucuresti' => 'Bucuresti',
        'Buzau' => 'Buzau',
        'Caras Severin' => 'Caras Severin',
        'Calarasi' => 'Calarasi',
        'Cluj' => 'Cluj',
        'Constanta' => 'Constanta',
        'Covasna' => 'Covasna',
        'Dambovita' => 'Dambovita',
        'Dolj' => 'Dolj',
        'Galati' => 'Galati',
        'Giurgiu' => 'Giurgiu',
        'Gorj' => 'Gorj',
        'Harghita' => 'Harghita',
        'Hunedoara' => 'Hunedoara',
        'Ialomita' => 'Ialomita',
        'Iasi' => 'Iasi',
        'Ilfov' => 'Ilfov',
        'Maramures' => 'Maramures',
        'Mehedinti' => 'Mehedinti',
        'Mures' => 'Mures',
        'Neamt' => 'Neamt',
        'Olt' => 'Olt',
        'Prahova' => 'Prahova',
        'Satu Mare' => 'Satu Mare',
        'Salaj' => 'Salaj',
        'Sibiu' => 'Sibiu',
        'Suceava' => 'Suceava',
        'Teleorman' => 'Teleorman',
        'Timis' => 'Timis',
        'Tulcea' => 'Tulcea',
        'Vaslui' => 'Vaslui',
        'Valcea' => 'Valcea',
        'Vrancea' => 'Vrancea',
    ],
];
